# Generated by Django 5.2 on 2025-04-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Images_news')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_news', models.TextField()),
                ('date_news', models.DateField()),
                ('short_news', models.TextField()),
                ('text_long_news', models.TextField()),
                ('pin', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.image_news')),
            ],
        ),
    ]
